name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*

jobs:
  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest
    
    env:
      MONGO_URI: 'mongodb+srv://superuser:${{ secrets.MONGO_PASSWORD }}@supercluster.d83jj.mongodb.net/superData'
      NODE_ENV: test
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Cache NPM Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: '${{ runner.os }}--node-modules-${{ hashFiles(''package-lock.json'') }}'

      - name: Setup NodeJS Version
        uses: actions/setup-node@v4
        with:
          node-version: 20
  
      - name: Install Dependencies
        run: npm ci
  
      - name: Unit Testing
        run: npm test
        
      - name: Archive Test Result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Mocha-Test-Result
          path: test-results.xml

  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    
    env:
      MONGO_URI: 'mongodb+srv://superuser:${{ secrets.MONGO_PASSWORD }}@supercluster.d83jj.mongodb.net/superData'
      NODE_ENV: test
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Run Coverage
        continue-on-error: true
        run: npm run coverage
      
      - name: Upload Artifact
        needs: Install Dependencies
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Code-Coverage-Report
          path: coverage
          retention-days: 5

